backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "blog"
    label: "Статті Блогу"
    folder: "blog"
    create: true
    slug: "article-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок статті", name: "title", widget: "string"}
      - {label: "Дата публікації", name: "date", widget: "datetime"}
      - {label: "Головне фото", name: "image", widget: "image"}
      - {label: "Короткий опис", name: "description", widget: "text"}
      - {label: "Текст статті", name: "body", widget: "markdown"}

  - name: "schedule_data"
    label: "Графік"
    files:
      - label: "Зайняті дати"
        name: "booked_dates"
        file: "booked-dates.json"
        fields:
          - {label: "Дані графіка", name: "content", widget: "text"}
